server.port: 8080

spring:
  datasource:
    url: jdbc:mysql://db:3306/twittercolourmap
    username: twittercolourmapuser
    password: 2jA9yK4jp7hJ7798QoHuyJEyMg77Gy
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect

---

spring:
  profiles: dev
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      dialect: org.hibernate.dialect.MySQL5Dialect

logging:
  level:
    co.timlong.twittercolourmap: TRACE
    #reactor.ipc.netty: DEBUG